### ISSUE TITLE
Exporter displaying traceback on target weblink

### ISSUE THREAD

**Issue by tmysl** [znerol/prometheus-pve-exporter#1]
Hello, when i start the exporter and go to http://10.0.1.14:9221/pve?target=10.0.1.14 (ip is of my proxmox host and the exporter as well, i get the following traceback: 

```Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pve_exporter/http.py", line 44, in do_GET
    output = collect_pve(self._config[module], target)
  File "/usr/local/lib/python2.7/dist-packages/pve_exporter/collector.py", line 207, in collect_pve
    return generate_latest(registry)
  File "/usr/local/lib/python2.7/dist-packages/prometheus_client/exposition.py", line 63, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python2.7/dist-packages/prometheus_client/core.py", line 97, in collect
    for metric in collector.collect():
  File "/usr/local/lib/python2.7/dist-packages/pve_exporter/collector.py", line 84, in collect
    del node['online']
KeyError: 'online'```

**Comment by znerol** [comment]
Thanks for the report. I pushed a fix for this into branch `bug/master/1-cluster-key-error`. Would you mind checking whether that fixes the problem and report back here?

**Comment by tmysl** [comment]
I'm seeing the same error against the branch (did a pip uninstall . followed by a pip install . --upgrade) logs are printing the following on the host: ```/usr/local/bin/pve_exporter /opt/prometheus-pve-exporter/pve.yml
10.0.1.39 - - [09/Oct/2017 08:53:55] "GET /pve?target=10.0.1.14 HTTP/1.1" 500 -
172.17.0.3 - - [09/Oct/2017 08:54:04] "GET /pve?module=default HTTP/1.1" 500 -
172.17.0.3 - - [09/Oct/2017 08:55:04] "GET /pve?module=default HTTP/1.1" 500 -```

Heres my prometheus.yml just to be helpul, its running via docker
`  - job_name: 'pve'
    static_configs:
      - targets:
        - 10.0.1.14:9221  # Proxmox VE node with PVE exporter.
    metrics_path: /pve
    params:
      module: [default]`

**Comment by znerol** [comment]
Sorry for that, I currently only have access to a single-node pve. Apparently the output from a cluster is a bit different. Do you see the same trace or is it a different one this time?

**Comment by znerol** [comment]
Found another place where that could be a problem. Do you mind pulling and trying again?
