### ISSUE TITLE
Only the first Disk 

### ISSUE THREAD

**Issue by elchaka** [znerol/prometheus-pve-exporter#12]
Hi,
it seems, that the pve_exporter is only getting one of (i.e.) four disks:

pve_disk_write_bytes{id="qemu/999"} 743841035264.0
pve_disk_usage_bytes{id="qemu/999"} 0.0
pve_disk_size_bytes{id="qemu/999"} 34359738368.0
pve_disk_read_bytes{id="qemu/999"} 279691497472.0

My VM (999) has
scsi0: cephcluster:vm-999-disk-1,discard=on,size=32G
scsi1: cephcluster:vm-999-disk-2,backup=0,size=2T
scsi2: cephcluster:vm-999-disk-5,backup=0,discard=on,size=20T
scsi3: cephcluster:vm-999-disk-3,size=5T

am i doing something wrong?

**Comment by elchaka** [comment]
Does the "pve_disk_write_bytes" and "pve_disk_read_bytes" only relates to the first disk "vm-999-disk-1" or is this the sum of "all disks"?

**Comment by znerol** [comment]
To be honest, I'm not quite sure whats happening here. Basically we just read out the Proxmox API using [Proxmoxer](https://pypi.python.org/pypi/proxmoxer). I currently cannot tell whether the API or the Proxmoxer client are delivering all the necessary results. Or maybe we are not interpreting them properly.

**Comment by znerol** [comment]
This is a limitation of the Proxmox API. We are getting our metrics from [cluster/resources](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/cluster/resources). That endpoint only reports usage for the startup disk.
