### ISSUE TITLE
cpu usage???

### ISSUE THREAD

**Issue by abashkindenis** [znerol/prometheus-pve-exporter#21]
Tell me what about cpu usage?
shows completely different meanings between.
For example, proxymox CPU usage 4.52%, and in monitoring 0.42, etc.
I don’t understand why.

**Comment by znerol** [comment]
The proxomx API provides cpu usage is a number between 0 and 1. This is also exactly the value exported by us as the `pve_cpu_usage_ratio` metric. Thus you can multiple the number reported by `prometheus-pve-exporter` with 100 in order to get a percentage.

**Comment by abashkindenis** [comment]
> API Proxomx обеспечивает использование ЦП в виде числа от 0 до 1. Это также значение, экспортируемое нами в качестве `pve_cpu_usage_ratio`показателя. Таким образом, вы можете умножить число на `prometheus-pve-exporter`100, чтобы получить процент.


I multiply the resulting value by 100 and get the processor load?

**Comment by znerol** [comment]
![pve-cpu-usage-ratio](https://user-images.githubusercontent.com/23288/72969390-aa1b7800-3dc5-11ea-888c-2c6ddc227d71.png)
