### ISSUE TITLE
command pve_exporter not working

### ISSUE THREAD

**Issue by smilebasti** [znerol/prometheus-pve-exporter#24]
Hi, 
i was just trying to install everything as it looked great but i am unable to find the config file.
The command: pve_export config troughs me an Error. pve_exporter -h works.
Details on the attached picture.
![image](https://user-images.githubusercontent.com/60941345/80744482-086f9980-8b1f-11ea-9b43-d2d52498be90.png)

Thanks ahead for your help.

**Comment by znerol** [comment]
Please note that `[config]`, `[port]` and `[address]` are positional arguments. Specify a path to the `pve.yml` configuration file as the first positional argument, the other ones are optional. You can find an example for `pve.yml` in the repository and also in the wiki. Place that example, e.g., in `/etc/pve.yml`. Then start `pve_exporter` like this:

    pve_exporter /etc/pve.yml

Note that there is an example for a systemd unit in the wiki as well.

HTH

**Comment by smilebasti** [comment]
Ok thanks that worked but i ran into a different error.

403 Forbidden: Permission check failed (/, Sys.Audit) - {"data":null}

I am getting this Error when trying to access (my) http://localhost:9221/pve?target=1.2.3.4
Couldn't find anything about this Error.
Hoping that you also can help me with this.

**Comment by znerol** [comment]
Where did you install `pve_exporter`? On a proxmox host or on another machine?

The URL in the README is an example. Replace `localhost` with the hostname or IP address where `pve_exporter` is running and `1.2.3.4` with the hostname or IP address of your Proxmox PVE host.

**Comment by smilebasti** [comment]
Thanks a had a line double in the configuration file in prometheus.
