### ISSUE TITLE
500 Internal Server Error type object argument after ** must be a mapping, not NoneType

### ISSUE THREAD

**Issue by Mr-Kane** [znerol/prometheus-pve-exporter#25]
Hi-
Trying to get this up and running and keep running into a 500 error I cannot seem to figure out. 

Running the exporter on a proxmox node and prometheus remote.

journal on proxmox shows a failed get request.
` "GET /pve?module=default HTTP/1.1" 500 -`

UI and a curl shows this error-

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>type object argument after ** must be a mapping, not NoneType</p>`

I cannot for the life of me figure this out so any help would be great! Let me know what you need and I'll get it for you.

Used this guide here to get it installed if that helps any.
https://blog.zwindler.fr/2020/01/06/proxmox-ve-prometheus/?unapproved=21086&moderation-hash=07cf6a6aa2cbec783032cc651e69b38a#comment-21086

**Comment by znerol** [comment]
You are absolutely right, the error message is not helpful at all. Luckily the `**` operator is only used twice, and the most likely problem is that `config` is `None` in [collect_pve](https://github.com/znerol/prometheus-pve-exporter/blob/c63cbdfe40c90b696d4ffe66df8e42a1f8392cdc/src/pve_exporter/collector.py#L291).

The `module` url parameter maps to toplevel keys in the config file. Thus make sure you have the [default](https://github.com/znerol/prometheus-pve-exporter/blob/c63cbdfe40c90b696d4ffe66df8e42a1f8392cdc/pve.yml#L1) toplevel key in your YAML configuration file.

HTH

**Comment by znerol** [comment]
Opened #25 and #26 to avoid problems like this in the future.

**Comment by znerol** [comment]
Released version 1.2.1 with error handling and config validation improvements. Please open a new issue if problems persist.

**Comment by Mr-Kane** [comment]
Appreciate the quick response! I'll give this a go tomorrow when I have a few minutes. Thanks again!

**Comment by Mr-Kane** [comment]
error handling helped greatly. the service is now up and running and working beautifully.
