### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by Madic-** [znerol/prometheus-pve-exporter#6]
Can you add IPv6 support? So that the http server also listens on ::9221 if on dual stack. I would supply a patch but I have nearly zero python knowledge

**Comment by znerol** [comment]
Yes, makes sense. This seems to be surprisingly difficult to implement in a platform independent way though. Result of a quick research:

* https://bugs.python.org/issue20215
* https://bugs.python.org/issue24209
* https://gist.github.com/akorobov/7903307
* https://code.activestate.com/recipes/578504-server-supporting-ipv4-and-ipv6/
* https://github.com/certbot/certbot/pull/4773

**Comment by Madic-** [comment]
Maybe you can take a look at the pihole exporter https://github.com/dr1s/pihole_exporter.py
It's also using python3 and listens on IPv6. Though I don't know how platform independent this implementation is

**Comment by znerol** [comment]
Oh, thanks. It looks like that they use [flask](https://pypi.python.org/pypi/Flask/). Might be justified to pull in that dependency instead of trying to work around the limitations of the built-in http server.

**Comment by znerol** [comment]
Can you take a look at PR #7 and test whether that works in your setup?

The cli has a new argument (`address`). You can specify any IPv4 or IPv6 address there (use `::` on a dual-stack machine, then it should listen on all interfaces, IPv4 as well as IPv6).

**Comment by Madic-** [comment]
It works. I created a new python3 virtual environment, installed the branch and ran it with the following command: /opt/pve-exporter/bin/pve_exporter /etc/prometheus/pve.yml 9221 ::

It's listening on tcp6 ::9221 and reachable via IPv4 and every IPv6 address.

Thank you very much for your response and help. Your exporter was one of the few without IPv6 :)

**Comment by znerol** [comment]
> Your exporter was one of the few without IPv6 :)

Thats probably because most of the other exporters switched to go (which has no problem with IPv6 out of the box). But AFAIK there are no Python bindings for the Proxmox API.

**Comment by znerol** [comment]
Released 1.1.0 with IPv6 support
