### ISSUE TITLE
URLs parameters for target not interpreted

### ISSUE THREAD

**Issue by yohannprigent** [znerol/prometheus-pve-exporter#9]
Hi,

If I use http://prometheus:9221/pve?target=10.1.1.1&module=default
I have the error 

`HTTPSConnectionPool(host='localhost', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1d961afa10>: Failed to establish a new connection: [Errno 111] Connection refused',))`

**Comment by znerol** [comment]
This looks like pve exporter is trying to connect to `localhost`. I guess this might be a regression after #7 

Can you test whether this works using a previous version (i.e. 1.0.0 instead of 1.1.0)

**Comment by znerol** [comment]
Pushed PR #10 which should fix the problem. Would be highly appreciated if you have a chance to test that.
